// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8Dk3KEKz6oFb3eVh5Ix49VFhcEuXioM',
    appId: '1:402423441604:web:0cabe0188e4f80e8b04191',
    messagingSenderId: '402423441604',
    projectId: 'viserlab-global-app',
    authDomain: 'viserlab-global-app.firebaseapp.com',
    storageBucket: 'viserlab-global-app.appspot.com',
    measurementId: 'G-BLRBH5LGBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVkdLgv2PcZCamYvw00aoG-mQmVTHndw4',
    appId: '1:402423441604:android:2b188fe5518dcb07b04191',
    messagingSenderId: '402423441604',
    projectId: 'viserlab-global-app',
    storageBucket: 'viserlab-global-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdMJxGkkvLqa2d7i2sGJz8Bxr229Ugk5Y',
    appId: '1:402423441604:ios:149e20bb9219c95cb04191',
    messagingSenderId: '402423441604',
    projectId: 'viserlab-global-app',
    storageBucket: 'viserlab-global-app.appspot.com',
    androidClientId: '402423441604-53kvi2o82481m6b00j7o22l0pjcimfpg.apps.googleusercontent.com',
    iosClientId: '402423441604-h56qvj09192tnri44isi57cqjk13lsb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.xcashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdMJxGkkvLqa2d7i2sGJz8Bxr229Ugk5Y',
    appId: '1:402423441604:ios:149e20bb9219c95cb04191',
    messagingSenderId: '402423441604',
    projectId: 'viserlab-global-app',
    storageBucket: 'viserlab-global-app.appspot.com',
    androidClientId: '402423441604-53kvi2o82481m6b00j7o22l0pjcimfpg.apps.googleusercontent.com',
    iosClientId: '402423441604-h56qvj09192tnri44isi57cqjk13lsb9.apps.googleusercontent.com',
    iosBundleId: 'com.example.xcashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfAkI8p8wKmbwtUi9Cq-2V4m4_65hAuU0',
    appId: '1:402423441604:web:fc87949bd59ad8f3b04191',
    messagingSenderId: '402423441604',
    projectId: 'viserlab-global-app',
    authDomain: 'viserlab-global-app.firebaseapp.com',
    storageBucket: 'viserlab-global-app.appspot.com',
    measurementId: 'G-DZRJQ9L0SM',
  );

}